### ISSUE TITLE
Test failure with python 3.8

### ISSUE THREAD

**Issue by sanjayankur31** [pauldmccarthy/fsleyes-widgets#2]
Hello,

Was looking to update the Fedora rawhide package to 0.8. We've got python 3.8 there, and 2 tests fail: (also a few warnings)

```
=================================== FAILURES ===================================
_____________________________ test_reorder_events ______________________________
    def test_reorder_events():
>       run_with_wx(_test_reorder_events)
tests/test_widgetgrid.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/__init__.py:106: in run_with_wx
    raise raised[0]
tests/__init__.py:85: in wrap
    result[0] = func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def _test_reorder_events():
        realYield()
        frame = wx.GetApp().GetTopWindow()
        frame.SetSize((800, 600))
        sim   = wx.UIActionSimulator()
        grid  = widgetgrid.WidgetGrid(frame, style=widgetgrid.WG_DRAGGABLE_COLUMNS)
        sizer = wx.BoxSizer(wx.VERTICAL)
        frame.SetSizer(sizer)
        sizer.Add(grid, flag=wx.EXPAND, proportion=1)
    
        grid.ShowColLabels()
        grid.SetGridSize(1, 5)
    
        labels = ['col {}' .format(i) for i in range(5)]
        cells  = ['cell {}'.format(i) for i in range(5)]
    
        for i in range(5): grid.SetColLabel(i, labels[i])
        for i in range(5): grid.SetText(0,  i, cells[i])
    
        grid.Refresh()
        frame.Layout()
    
        class FakeEV(object):
    
            def __init__(self, evo):
                self.evo = evo
    
            def Skip(self):
                pass
    
            def GetEventObject(self):
                return self.evo
    
        # (clicked column, drop column, drop pos, expected order)
        tests = [
            (0, 0, 0.25, [0, 1, 2, 3, 4]),
            (0, 0, 0.75, [0, 1, 2, 3, 4]),
            (1, 1, 0.25, [0, 1, 2, 3, 4]),
            (1, 1, 0.75, [0, 1, 2, 3, 4]),
            (0, 1, 0.25, [0, 1, 2, 3, 4]),
            (1, 2, 0.25, [0, 1, 2, 3, 4]),
            (1, 0, 0.75, [0, 1, 2, 3, 4]),
            (2, 1, 0.75, [0, 1, 2, 3, 4]),
            (0, 1, 0.75, [1, 0, 2, 3, 4]),
            (1, 2, 0.75, [0, 2, 1, 3, 4]),
            (1, 0, 0.25, [1, 0, 2, 3, 4]),
            (2, 1, 0.25, [0, 2, 1, 3, 4]),
            (0, 2, 0.25, [1, 0, 2, 3, 4]),
            (0, 2, 0.75, [1, 2, 0, 3, 4]),
            (2, 0, 0.25, [2, 0, 1, 3, 4]),
            (2, 0, 0.75, [0, 2, 1, 3, 4]),
            (1, 3, 0.25, [0, 2, 1, 3, 4]),
            (1, 3, 0.75, [0, 2, 3, 1, 4]),
            (3, 1, 0.25, [0, 3, 1, 2, 4]),
            (3, 1, 0.75, [0, 1, 3, 2, 4]),
            (1, 4, 0.25, [0, 2, 3, 1, 4]),
            (1, 4, 0.75, [0, 2, 3, 4, 1]),
        ]
    
        realYield()
        for clickcol, dropcol, droppos, exporder in tests:
    
            cwidget = grid.colLabels[clickcol].GetParent()
            dwidget = grid.colLabels[dropcol] .GetParent()
    
            simmove(sim, cwidget, [0.5, 0.5])
            ev = FakeEV(cwidget)
            grid._WidgetGrid__onColumnLabelMouseDown(ev)
            realYield()
            simmove(sim, dwidget, [droppos, 0.5])
            realYield()
            grid._WidgetGrid__onColumnLabelMouseDrag(ev)
            realYield()
            ev.evo = dwidget
            grid._WidgetGrid__onColumnLabelMouseUp(ev)
            realYield()
    
            explabels = [labels[i] for i in exporder]
            gotlabels = grid.GetColLabels()
    
>           assert explabels == gotlabels
E           AssertionError: assert ['col 0', 'co...l 2', 'col 4'] == ['col 0', 'col...l 1', 'col 4']
E             At index 1 diff: 'col 3' != 'col 2'
E             Full diff:
E             - ['col 0', 'col 3', 'col 1', 'col 2', 'col 4']
E             ?                ^        ^        ^
E             + ['col 0', 'col 2', 'col 3', 'col 1', 'col 4']
E             ?                ^        ^        ^
tests/test_widgetgrid.py:159: AssertionError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/__init__.py", line 85, in wrap
    result[0] = func(*args, **kwargs)
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/test_widgetgrid.py", line 159, in _test_reorder_events
    assert explabels == gotlabels
AssertionError: assert ['col 0', 'co...l 2', 'col 4'] == ['col 0', 'col...l 1', 'col 4']
  At index 1 diff: 'col 3' != 'col 2'
  Full diff:
  - ['col 0', 'col 3', 'col 1', 'col 2', 'col 4']
  ?                ^        ^        ^
  + ['col 0', 'col 2', 'col 3', 'col 1', 'col 4']
  ?                ^        ^        ^
________________________ test_reorder_events_draglimit _________________________
    def test_reorder_events_draglimit():
>       run_with_wx(_test_reorder_events_draglimit)
tests/test_widgetgrid.py:165: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/__init__.py:106: in run_with_wx
    raise raised[0]
tests/__init__.py:85: in wrap
    result[0] = func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def _test_reorder_events_draglimit():
        realYield()
        frame = wx.GetApp().GetTopWindow()
        frame.SetSize((800, 600))
        sim   = wx.UIActionSimulator()
        grid  = widgetgrid.WidgetGrid(frame, style=widgetgrid.WG_DRAGGABLE_COLUMNS)
        sizer = wx.BoxSizer(wx.VERTICAL)
        frame.SetSizer(sizer)
        sizer.Add(grid, flag=wx.EXPAND, proportion=1)
    
        grid.ShowColLabels()
        grid.SetGridSize(1, 5)
        grid.SetDragLimit(2)
    
        labels = ['col {}' .format(i) for i in range(5)]
        cells  = ['cell {}'.format(i) for i in range(5)]
    
        for i in range(5): grid.SetColLabel(i, labels[i])
        for i in range(5): grid.SetText(0,  i, cells[i])
    
        grid.Refresh()
        frame.Layout()
    
        class FakeEV(object):
    
            def __init__(self, evo):
                self.evo = evo
    
            def Skip(self):
                pass
    
            def GetEventObject(self):
                return self.evo
    
        # (clicked column, drop column, drop pos, expected order)
        tests = [
            (0, 1, 0.75, [1, 0, 2, 3, 4]),
            (1, 2, 0.75, [0, 2, 1, 3, 4]),
            (1, 0, 0.25, [1, 0, 2, 3, 4]),
            (2, 1, 0.25, [0, 2, 1, 3, 4]),
    
            # drop is past drag limit -> clamp
            (0, 3, 0.75, [1, 2, 0, 3, 4]),
            (0, 4, 0.75, [1, 2, 0, 3, 4]),
    
            # past drag limit -> no-ops
            (3, 1, 0.25, [0, 1, 2, 3, 4]),
            (3, 4, 0.75, [0, 1, 2, 3, 4]),
            (4, 3, 0.25, [0, 1, 2, 3, 4]),
        ]
    
        realYield()
        for clickcol, dropcol, droppos, exporder in tests:
    
            cwidget = grid.colLabels[clickcol].GetParent()
            dwidget = grid.colLabels[dropcol] .GetParent()
    
            simmove(sim, cwidget, [0.5, 0.5])
            ev = FakeEV(cwidget)
            grid._WidgetGrid__onColumnLabelMouseDown(ev)
            realYield()
            simmove(sim, dwidget, [droppos, 0.5])
            realYield()
            grid._WidgetGrid__onColumnLabelMouseDrag(ev)
            realYield()
            ev.evo = dwidget
            grid._WidgetGrid__onColumnLabelMouseUp(ev)
            realYield()
    
            explabels = [labels[i] for i in exporder]
            gotlabels = grid.GetColLabels()
    
>           assert explabels == gotlabels
E           AssertionError: assert ['col 1', 'co...l 3', 'col 4'] == ['col 0', 'col...l 3', 'col 4']
E             At index 0 diff: 'col 1' != 'col 0'
E             Full diff:
E             - ['col 1', 'col 2', 'col 0', 'col 3', 'col 4']
E             ?       ^        ^        ^
E             + ['col 0', 'col 1', 'col 2', 'col 3', 'col 4']
E             ?       ^        ^        ^
tests/test_widgetgrid.py:238: AssertionError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/__init__.py", line 85, in wrap
    result[0] = func(*args, **kwargs)
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/test_widgetgrid.py", line 238, in _test_reorder_events_draglimit
    assert explabels == gotlabels
AssertionError: assert ['col 1', 'co...l 3', 'col 4'] == ['col 0', 'col...l 3', 'col 4']
  At index 0 diff: 'col 1' != 'col 0'
  Full diff:
  - ['col 1', 'col 2', 'col 0', 'col 3', 'col 4']
  ?       ^        ^        ^
  + ['col 0', 'col 1', 'col 2', 'col 3', 'col 4']
  ?       ^        ^        ^
=============================== warnings summary ===============================
tests/test_progress.py:62
  /builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/test_progress.py:62: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    if endfunc is not 'Destroy':
tests/test_overlay.py::test_textOverlay
tests/test_overlay.py::test_textOverlay
  /builddir/build/BUILD/fsleyes-widgets-0.8.0/fsleyes_widgets/utils/overlay.py:48: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    dc.DrawRoundedRectangle(x - 5, y - 5, tw + 10, th + 10, 2)
tests/test_overlay.py::test_textOverlay
tests/test_overlay.py::test_textOverlay
  /builddir/build/BUILD/fsleyes-widgets-0.8.0/fsleyes_widgets/utils/overlay.py:51: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    dc.DrawText(text, x, y)
tests/test_progress.py::test_runWithBounce
tests/test_progress.py::test_runWithBounce_cancel
  /builddir/build/BUILD/fsleyes-widgets-0.8.0/fsleyes_widgets/utils/progress.py:90: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    timer.Start(polltime * 1000, wx.TIMER_CONTINUOUS)
tests/test_runwindow.py::test_ProcessManager_run
tests/test_runwindow.py::test_ProcessManager_termProc
tests/test_runwindow.py::test_run
  /usr/lib64/python3.8/subprocess.py:819: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
    self.stdout = io.open(c2pread, 'rb', bufsize)
tests/test_textpanel.py::test_TextPanel
tests/test_textpanel.py::test_TextPanel
tests/test_textpanel.py::test_TextPanel
tests/test_textpanel.py::test_TextPanel
  /builddir/build/BUILD/fsleyes-widgets-0.8.0/fsleyes_widgets/textpanel.py:135: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    dc.DrawText(self.__text, x, y)
tests/test_textpanel.py::test_TextPanel
tests/test_textpanel.py::test_TextPanel
  /builddir/build/BUILD/fsleyes-widgets-0.8.0/fsleyes_widgets/textpanel.py:133: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    dc.DrawRotatedText(self.__text, x, paneH - y, 90)
tests/test_typedict.py::test_create
  /builddir/build/BUILD/fsleyes-widgets-0.8.0/fsleyes_widgets/utils/typedict.py:191: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
```

Complete build.log attached. Root log with complete package versions also attached:

[buildlog.txt](https://github.com/pauldmccarthy/fsleyes-widgets/files/3562488/buildlog.txt)
[rootlog.txt](https://github.com/pauldmccarthy/fsleyes-widgets/files/3562489/rootlog.txt)

**Comment by pauldmccarthy** [comment]
The failing tests are a bit sensitive to timing - I generate events and then wait for 10 milliseconds, assuming that 10 msecs is enough for `wxpython` to process the event. I guess it's not enough.

Would you be able to change the `realYield()` calls in those test functions to `realYield(50)`, and see if that fixes the problem?

**Comment by sanjayankur31** [comment]
I went a bit gung-ho and did this:

```
sed -i 's|realYield()|realYield(50)|g' tests/test_widgetgrid.py
```

The tests still failed, unfortunately:

```
=================================== FAILURES ===================================
_____________________________ test_reorder_events ______________________________
    def test_reorder_events():
>       run_with_wx(_test_reorder_events)
tests/test_widgetgrid.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/__init__.py:106: in run_with_wx
    raise raised[0]
tests/__init__.py:85: in wrap
    result[0] = func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def _test_reorder_events():
        realYield(50)
        frame = wx.GetApp().GetTopWindow()
        frame.SetSize((800, 600))
        sim   = wx.UIActionSimulator()
        grid  = widgetgrid.WidgetGrid(frame, style=widgetgrid.WG_DRAGGABLE_COLUMNS)
        sizer = wx.BoxSizer(wx.VERTICAL)
        frame.SetSizer(sizer)
        sizer.Add(grid, flag=wx.EXPAND, proportion=1)
    
        grid.ShowColLabels()
        grid.SetGridSize(1, 5)
    
        labels = ['col {}' .format(i) for i in range(5)]
        cells  = ['cell {}'.format(i) for i in range(5)]
    
        for i in range(5): grid.SetColLabel(i, labels[i])
        for i in range(5): grid.SetText(0,  i, cells[i])
    
        grid.Refresh()
        frame.Layout()
    
        class FakeEV(object):
    
            def __init__(self, evo):
                self.evo = evo
    
            def Skip(self):
                pass
    
            def GetEventObject(self):
                return self.evo
    
        # (clicked column, drop column, drop pos, expected order)
        tests = [
            (0, 0, 0.25, [0, 1, 2, 3, 4]),
            (0, 0, 0.75, [0, 1, 2, 3, 4]),
            (1, 1, 0.25, [0, 1, 2, 3, 4]),
            (1, 1, 0.75, [0, 1, 2, 3, 4]),
            (0, 1, 0.25, [0, 1, 2, 3, 4]),
            (1, 2, 0.25, [0, 1, 2, 3, 4]),
            (1, 0, 0.75, [0, 1, 2, 3, 4]),
            (2, 1, 0.75, [0, 1, 2, 3, 4]),
            (0, 1, 0.75, [1, 0, 2, 3, 4]),
            (1, 2, 0.75, [0, 2, 1, 3, 4]),
            (1, 0, 0.25, [1, 0, 2, 3, 4]),
            (2, 1, 0.25, [0, 2, 1, 3, 4]),
            (0, 2, 0.25, [1, 0, 2, 3, 4]),
            (0, 2, 0.75, [1, 2, 0, 3, 4]),
            (2, 0, 0.25, [2, 0, 1, 3, 4]),
            (2, 0, 0.75, [0, 2, 1, 3, 4]),
            (1, 3, 0.25, [0, 2, 1, 3, 4]),
            (1, 3, 0.75, [0, 2, 3, 1, 4]),
            (3, 1, 0.25, [0, 3, 1, 2, 4]),
            (3, 1, 0.75, [0, 1, 3, 2, 4]),
            (1, 4, 0.25, [0, 2, 3, 1, 4]),
            (1, 4, 0.75, [0, 2, 3, 4, 1]),
        ]
    
        realYield(50)
        for clickcol, dropcol, droppos, exporder in tests:
    
            cwidget = grid.colLabels[clickcol].GetParent()
            dwidget = grid.colLabels[dropcol] .GetParent()
    
            simmove(sim, cwidget, [0.5, 0.5])
            ev = FakeEV(cwidget)
            grid._WidgetGrid__onColumnLabelMouseDown(ev)
            realYield(50)
            simmove(sim, dwidget, [droppos, 0.5])
            realYield(50)
            grid._WidgetGrid__onColumnLabelMouseDrag(ev)
            realYield(50)
            ev.evo = dwidget
            grid._WidgetGrid__onColumnLabelMouseUp(ev)
            realYield(50)
    
            explabels = [labels[i] for i in exporder]
            gotlabels = grid.GetColLabels()
    
>           assert explabels == gotlabels
E           AssertionError: assert ['col 0', 'co...l 2', 'col 4'] == ['col 0', 'col...l 1', 'col 4']
E             At index 1 diff: 'col 3' != 'col 2'
E             Full diff:
E             - ['col 0', 'col 3', 'col 1', 'col 2', 'col 4']
E             ?                ^        ^        ^
E             + ['col 0', 'col 2', 'col 3', 'col 1', 'col 4']
E             ?                ^        ^        ^
tests/test_widgetgrid.py:159: AssertionError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/__init__.py", line 85, in wrap
    result[0] = func(*args, **kwargs)
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/test_widgetgrid.py", line 159, in _test_reorder_events
    assert explabels == gotlabels
AssertionError: assert ['col 0', 'co...l 2', 'col 4'] == ['col 0', 'col...l 1', 'col 4']
  At index 1 diff: 'col 3' != 'col 2'
  Full diff:
  - ['col 0', 'col 3', 'col 1', 'col 2', 'col 4']
  ?                ^        ^        ^
  + ['col 0', 'col 2', 'col 3', 'col 1', 'col 4']
  ?                ^        ^        ^
________________________ test_reorder_events_draglimit _________________________
    def test_reorder_events_draglimit():
>       run_with_wx(_test_reorder_events_draglimit)
tests/test_widgetgrid.py:165: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/__init__.py:106: in run_with_wx
    raise raised[0]
tests/__init__.py:85: in wrap
    result[0] = func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def _test_reorder_events_draglimit():
        realYield(50)
        frame = wx.GetApp().GetTopWindow()
        frame.SetSize((800, 600))
        sim   = wx.UIActionSimulator()
        grid  = widgetgrid.WidgetGrid(frame, style=widgetgrid.WG_DRAGGABLE_COLUMNS)
        sizer = wx.BoxSizer(wx.VERTICAL)
        frame.SetSizer(sizer)
        sizer.Add(grid, flag=wx.EXPAND, proportion=1)
    
        grid.ShowColLabels()
        grid.SetGridSize(1, 5)
        grid.SetDragLimit(2)
    
        labels = ['col {}' .format(i) for i in range(5)]
        cells  = ['cell {}'.format(i) for i in range(5)]
    
        for i in range(5): grid.SetColLabel(i, labels[i])
        for i in range(5): grid.SetText(0,  i, cells[i])
    
        grid.Refresh()
        frame.Layout()
    
        class FakeEV(object):
    
            def __init__(self, evo):
                self.evo = evo
    
            def Skip(self):
                pass
    
            def GetEventObject(self):
                return self.evo
    
        # (clicked column, drop column, drop pos, expected order)
        tests = [
            (0, 1, 0.75, [1, 0, 2, 3, 4]),
            (1, 2, 0.75, [0, 2, 1, 3, 4]),
            (1, 0, 0.25, [1, 0, 2, 3, 4]),
            (2, 1, 0.25, [0, 2, 1, 3, 4]),
    
            # drop is past drag limit -> clamp
            (0, 3, 0.75, [1, 2, 0, 3, 4]),
            (0, 4, 0.75, [1, 2, 0, 3, 4]),
    
            # past drag limit -> no-ops
            (3, 1, 0.25, [0, 1, 2, 3, 4]),
            (3, 4, 0.75, [0, 1, 2, 3, 4]),
            (4, 3, 0.25, [0, 1, 2, 3, 4]),
        ]
    
        realYield(50)
        for clickcol, dropcol, droppos, exporder in tests:
    
            cwidget = grid.colLabels[clickcol].GetParent()
            dwidget = grid.colLabels[dropcol] .GetParent()
    
            simmove(sim, cwidget, [0.5, 0.5])
            ev = FakeEV(cwidget)
            grid._WidgetGrid__onColumnLabelMouseDown(ev)
            realYield(50)
            simmove(sim, dwidget, [droppos, 0.5])
            realYield(50)
            grid._WidgetGrid__onColumnLabelMouseDrag(ev)
            realYield(50)
            ev.evo = dwidget
            grid._WidgetGrid__onColumnLabelMouseUp(ev)
            realYield(50)
    
            explabels = [labels[i] for i in exporder]
            gotlabels = grid.GetColLabels()
    
>           assert explabels == gotlabels
E           AssertionError: assert ['col 1', 'co...l 3', 'col 4'] == ['col 0', 'col...l 3', 'col 4']
E             At index 0 diff: 'col 1' != 'col 0'
E             Full diff:
E             - ['col 1', 'col 2', 'col 0', 'col 3', 'col 4']
E             ?       ^        ^        ^
E             + ['col 0', 'col 1', 'col 2', 'col 3', 'col 4']
E             ?       ^        ^        ^
tests/test_widgetgrid.py:238: AssertionError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/__init__.py", line 85, in wrap
    result[0] = func(*args, **kwargs)
  File "/builddir/build/BUILD/fsleyes-widgets-0.8.0/tests/test_widgetgrid.py", line 238, in _test_reorder_events_draglimit
    assert explabels == gotlabels
AssertionError: assert ['col 1', 'co...l 3', 'col 4'] == ['col 0', 'col...l 3', 'col 4']
  At index 0 diff: 'col 1' != 'col 0'
  Full diff:
  - ['col 1', 'col 2', 'col 0', 'col 3', 'col 4']
  ?       ^        ^        ^
  + ['col 0', 'col 1', 'col 2', 'col 3', 'col 4']
  ?       ^        ^        ^
=============================== warnings summary ===============================
```

**Comment by pauldmccarthy** [comment]
Sorry for the repeated delays ... aah, I've just had a thought. I recall getting these same errors when running the tests like so:

```
xvfb-run -a -s "-screen 0 640x480x24" pytest
```

The tests were failing because the virtual screen was too small, so the mouse locations were not precise enough. I solved it by bumping up the display size:

```
xvfb-run -a -s "-screen 0 1920x1200x24" pytest
```

Does that solve it for you? 

I am about to start the process of upgrading to gtk3, and adding in a test python3.8 environment, so will attempt to reproduce the issue.

**Comment by pauldmccarthy** [comment]
So in an `ubuntu:18.04` docker container with python 3.8 and wxpython 4.0.6 (compiled from source), running with `xvfb-run -a -s `-screen 640x480x24` I reproduced the test failures. But the tests passed when I used `xvfb-run -a -s `-screen 1920x1280x24`.

(I've got other test failures which weren't resolved with the increased display size - am glad that they're passing for you!)

**Comment by sanjayankur31** [comment]
Ah! That seems to work! I've updated the spec file accordingly. Closing this issue.

**Comment by pauldmccarthy** [comment]
Goodness, that took a while to figure out. My own py38/gtk3 failures were because wxpython 4.0.6 was being bundled with a version of wxwidgets that had had xtest support stripped out, so most of the event simulation was broken. Moving to the master branch of wxpython fixes everything. Phew.
